pastix:
  script:
    - git submodule init
    - git submodule update
    - mkdir build
    - cd build
    - cmake ..
    - make -j2
    - ctest -D ExperimentalTest
    #- if [ `which valgrind` ]; then ctest -D ExperimentalMemCheck; fi

pages:
  script:
  - echo "J'ai reussi" > index.html
  artifacts:
    paths:
    - public
