stages:
  - build
  - test
  - sonar
  - doc

build_pastix:
  stage: build
  artifacts:
    name: pastix_build
    expire_in: 42 minutes
    untracked: true
    paths:
      - build
      - pastix-build.log
  script:
    - source .gitlab-ci-env.sh
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=${PWD}/../install -DBUILD_SHARED_LIBS=ON -DPASTIX_WITH_STARPU=ON -DPASTIX_WITH_PARSEC=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_FLAGS="-O0 -g -fPIC --coverage -Wall -fdiagnostics-show-option -fno-inline" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
    - make -j2 | tee ../pastix-build.log
    - make install

test_pastix:
  stage: test
  dependencies:
  - build_pastix
  artifacts:
    name: pastix_analysis
    expire_in: 1 week
    paths:
      - pastix-build.log
      - pastix.lcov
      - coverage/
      - pastix-coverage.xml
      - pastix-cppcheck.xml
      - pastix-rats.xml
  script:
    - source .gitlab-ci-env.sh
    - source install/bin/pastix_env.sh
    - (cd build && ctest -D ExperimentalTest)
    - lcov --directory build --capture --output-file pastix.lcov
    - genhtml -o coverage pastix.lcov
    - ${COBERTURA_PATH}/lcov_cobertura.py pastix.lcov --output pastix-coverage.xml
    - export SOURCES_TO_ANALYZE="build bcsc blend common example graph include kernels order refinement sopalin spm symbol test"
    - cppcheck -v -f --language=c --platform=unix64 --enable=all --xml --xml-version=2 --suppress=missingIncludeSystem -UPARSEC_DEBUG_NOISIER -DPINS_ENABLE ${SOURCES_TO_ANALYZE} 2> pastix-cppcheck.xml
    - rats -w 3 --xml ${SOURCES_TO_ANALYZE} > pastix-rats.xml

sonar_pastix:
  stage: sonar
  dependencies:
  - build_pastix
  - test_pastix
  artifacts:
    name: pastix_sonar
    expire_in: 1 week
    paths:
      - sonar.log
  script:
    - source .gitlab-ci-env.sh
    - sonar-scanner -X > sonar.log
  only:
    - master@pastix/pastix

pages:
  stage: doc
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DBUILD_DOCUMENTATION=ON
    - make
    - mv docs/out/html ../public/
  artifacts:
    paths:
      - public
  only:
    - master@pastix/pastix

