image: hpclib/hiepacs

stages:
  - build
  - test
  - sonar
  - doc

build_pastix:
  stage: build
  artifacts:
    name: pastix_build
    expire_in: 42 minutes
    untracked: true
  script:
    - source .gitlab-ci-env.sh
    - git submodule update --init --recursive
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=${PWD}/../install -DBUILD_SHARED_LIBS=ON -DPASTIX_WITH_STARPU=ON -DPASTIX_WITH_PARSEC=ON -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_C_FLAGS="-O0 -g -fPIC --coverage -Wall -fdiagnostics-show-option -fno-inline" -DCMAKE_EXE_LINKER_FLAGS="--coverage" -DPASTIX_INT64=OFF
    - make -j 4 | tee ../pastix-build.log
    - make install | tee -a ../pastix-build.log
  only:
    - branches
    - master@pastix/pastix
    - master@solverstack/pastix

test_pastix:
  stage: test
  dependencies:
    - build_pastix
  artifacts:
    name: pastix_test
    expire_in: 42 minutes
    paths:
      - coverage.tar.bz2
  script:
    - source .gitlab-ci-env.sh
    - source install/bin/pastix_env.sh
    - (cd build && ctest -D ExperimentalTest)
    - find -name "*.gcda" | xargs tar cjf coverage.tar.bz2
  only:
    - branches
    - master@pastix/pastix
    - master@solverstack/pastix

sonar_pastix:
  stage: sonar
  dependencies:
    - build_pastix
    - test_pastix
  artifacts:
    name: pastix_sonar
    expire_in: 1 week
    paths:
      - pastix.lcov
      - coverage/
      - pastix-coverage.xml
      - pastix-cppcheck.xml
      - pastix-rats.xml
      - sonar.log
  script:
    - source .gitlab-ci-env.sh
    - tar xjf coverage.tar.bz2
    - lcov --directory build --capture --output-file pastix.lcov
    - genhtml -o coverage pastix.lcov
    - lcov_cobertura.py pastix.lcov --output pastix-coverage.xml
    - ./.gitlab-ci-filelist.sh
    - cppcheck -v -f --language=c --platform=unix64 --enable=all --xml --xml-version=2 --suppress=missingIncludeSystem -UPARSEC_PROF_DRY_BODY -UPARSEC_PROF_TRACE -UPARSEC_PROF_GRAPHER -UPARSEC_SIM -UPARSEC_DEBUG_NOISIER -DPINS_ENABLE --file-list=./filelist.txt 2> pastix-cppcheck.xml
    - rats -w 3 --xml `cat filelist.txt` > pastix-rats.xml
    - echo -n "sonar.inclusions=" >> sonar-project.properties
    - cat filelist.txt | xargs echo | sed 's/ /, /g' >> sonar-project.properties
    - sonar-scanner -X > sonar.log
  only:
    - master@pastix/pastix

pages:
  stage: doc
  dependencies:
    - build_pastix
  script:
    - source .gitlab-ci-env.sh
    - git submodule update --init --recursive
    - mkdir -p build
    - cd build
    - cmake .. -DBUILD_DOCUMENTATION=ON -DPASTIX_WITH_STARPU=ON -DPASTIX_WITH_PARSEC=ON -DPASTIX_INT64=OFF
    - make docs
    - mv docs/out/html ../public/
  artifacts:
    paths:
      - public
  only:
    - master@pastix/pastix

