---
image: registry.gitlab.inria.fr/solverstack/docker/distrib

stages:
  - bench
  - build
  - test
  - analyse
  - sonar
  - deploy

before_script:
  - git config --global --add safe.directory $CI_PROJECT_DIR
  - git config --global --add safe.directory $CI_PROJECT_DIR/cmake_modules/morse_cmake
  - git config --global --add safe.directory $CI_PROJECT_DIR/spm
  - git config --global --add safe.directory $CI_PROJECT_DIR/spm/cmake_modules/morse_cmake
  - git submodule update --init --recursive
  - source ${CI_PROJECT_DIR}/.gitlab/env.sh ${VERSION}
  - unset SPM_DIR # Make sure we don't use the installed spm
  - if [ ! -z "$SPM_DIR" ]; then source $SPM_DIR/bin/spm_env.sh; fi
  - echo "VERSION=${VERSION}"
  - mkdir -p build

include:
  - .gitlab/preliminary.yml
  - .gitlab/benchmark.yml
  - .gitlab/common.yml
  - .gitlab/build.yml
  - .gitlab/test.yml
  - .gitlab/test_wrapper.yml
  - .gitlab/coverage.yml
  - .gitlab/sonarqube.yml
  - .gitlab/pages.yml
  - .gitlab/release.yml
  - .gitlab/coverity.yml
