---
.build_script_template: &build_script
  stage: build
  tags: ["docker", "large"]
  artifacts:
    name: pastix_build_${VERSION}
    expire_in: 180 minutes
    untracked: true
    paths:
      - install-${VERSION}
      - build
      - pastix-build-${VERSION}.log
  script:
    - cd build
    - echo $VERSION | tee ${CI_PROJECT_DIR}/pastix-build-${VERSION}.log
    - cmake -DPASTIX_CI_VERSION=${VERSION}
            -DPASTIX_CI_BRANCH=${BRANCH}
            -C ${CI_PROJECT_DIR}/.gitlab/ci-test-initial-cache.cmake ${CI_PROJECT_DIR}
    - make -j 4    | tee -a ../pastix-build-${VERSION}.log
    - make install | tee -a ../pastix-build-${VERSION}.log
  only:
    - branches
    - master@pastix/pastix
    - master@solverstack/pastix

.build_script_template_seq: &build_script_seq
  extends:
    - .build_script_template
    - .only-branches-seq

.build_script_template_mpi: &build_script_mpi
  extends:
    - .build_script_template
    - .only-branches-mpi

build_pastix_seq:
  <<: *build_script_seq
  variables:
    VERSION: seq

build_pastix_mpi:
  <<: *build_script_mpi
  variables:
    VERSION: mpi
